---
apiVersion: v1
kind: Namespace
metadata:
  name: samplens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeploy
  namespace: samplens
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
     app: samplehtmlweb
  template:
    metadata:
      name: samplepod
      labels:
        app: samplehtmlweb
        version: v1
    spec:
      containers:
      - name: samplecontainer
        image: akshay0909/blogapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: samplesvc
  namespace: samplens
spec:
  type: NodePort
  selector:
    version: v1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
...
